name: fl_gpu
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - pyyaml
      - tqdm
      - jupyter
      - ipykernel
      - pillow
      - opacus
      - python-dotenv
